/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportLostRouteImport } from './routes/report-lost'
import { Route as ReportFoundRouteImport } from './routes/report-found'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactItemIdRouteImport } from './routes/contact.$itemId'
import { Route as ClaimItemIdRouteImport } from './routes/claim.$itemId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportLostRoute = ReportLostRouteImport.update({
  id: '/report-lost',
  path: '/report-lost',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFoundRoute = ReportFoundRouteImport.update({
  id: '/report-found',
  path: '/report-found',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactItemIdRoute = ContactItemIdRouteImport.update({
  id: '/contact/$itemId',
  path: '/contact/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimItemIdRoute = ClaimItemIdRouteImport.update({
  id: '/claim/$itemId',
  path: '/claim/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-found': typeof ReportFoundRoute
  '/report-lost': typeof ReportLostRoute
  '/search': typeof SearchRoute
  '/claim/$itemId': typeof ClaimItemIdRoute
  '/contact/$itemId': typeof ContactItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-found': typeof ReportFoundRoute
  '/report-lost': typeof ReportLostRoute
  '/search': typeof SearchRoute
  '/claim/$itemId': typeof ClaimItemIdRoute
  '/contact/$itemId': typeof ContactItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-found': typeof ReportFoundRoute
  '/report-lost': typeof ReportLostRoute
  '/search': typeof SearchRoute
  '/claim/$itemId': typeof ClaimItemIdRoute
  '/contact/$itemId': typeof ContactItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/matches'
    | '/profile'
    | '/register'
    | '/report-found'
    | '/report-lost'
    | '/search'
    | '/claim/$itemId'
    | '/contact/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/matches'
    | '/profile'
    | '/register'
    | '/report-found'
    | '/report-lost'
    | '/search'
    | '/claim/$itemId'
    | '/contact/$itemId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/matches'
    | '/profile'
    | '/register'
    | '/report-found'
    | '/report-lost'
    | '/search'
    | '/claim/$itemId'
    | '/contact/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportFoundRoute: typeof ReportFoundRoute
  ReportLostRoute: typeof ReportLostRoute
  SearchRoute: typeof SearchRoute
  ClaimItemIdRoute: typeof ClaimItemIdRoute
  ContactItemIdRoute: typeof ContactItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-lost': {
      id: '/report-lost'
      path: '/report-lost'
      fullPath: '/report-lost'
      preLoaderRoute: typeof ReportLostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-found': {
      id: '/report-found'
      path: '/report-found'
      fullPath: '/report-found'
      preLoaderRoute: typeof ReportFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/$itemId': {
      id: '/contact/$itemId'
      path: '/contact/$itemId'
      fullPath: '/contact/$itemId'
      preLoaderRoute: typeof ContactItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$itemId': {
      id: '/claim/$itemId'
      path: '/claim/$itemId'
      fullPath: '/claim/$itemId'
      preLoaderRoute: typeof ClaimItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportFoundRoute: ReportFoundRoute,
  ReportLostRoute: ReportLostRoute,
  SearchRoute: SearchRoute,
  ClaimItemIdRoute: ClaimItemIdRoute,
  ContactItemIdRoute: ContactItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
